### - with a body (to test 201 Created)
post http://localhost:3000/register
content-type: application/json

{
  "firstName": "Baz",
  "lastName": "Murphy"
}

### - with no firstName (to test 400 Bad Request)
post http://localhost:3000/register
content-type: application/json

{
  "lastName": "Murphy"
}

### - with no lastName (to test 400 Bad Request)
post http://localhost:3000/register
content-type: application/json

{
  "firstName": "Baz"
}

### - with no firstName and lastName (to test 400 Bad Request)
post http://localhost:3000/register
content-type: application/json

{}